local_settings_file_path: "/Users/balinderwalia/Documents/Work/aws_keys/settings_whisky01.json"
local_env_file_path: "/Users/balinderwalia/Documents/Work/aws_keys/.env_whisky01"
nginx_user_password: "!!REDACTED!!" # This is the password for the user www-data but must be encrypted using Ansible Vault
host_lan_ip: "10.24.5.250"
nginx_web_ui_enabled: "yes"
nginx_rest_api_server_enabled: ""
nginx_data_sync_enabled: "yes"
nginx_s3_proxy_pass_host_ip: "192.168.1.13"
nginx_s3_server_name: "s3.workstation.co.uk"
nginx_s3_cli_server_name: "s3-cli.workstation.co.uk"
nginx_k3s_dashboard_server_name: "k3s-dashboard.workstation.co.uk"
openresty_admin_secondary_color: "#D91656"