apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: node-app-secret
  namespace: default
spec:
  encryptedData:
    env_file: AgBXTzLt6M779SbcOX0H+I/LFut5Rp6z6LLCR8t9w8nMWrpeKJEibnRddeDV9GsXUrMBaGPv/n9SbZtoHlqq5Hzq38vNGiXPz+EcPviDFWq7HLBXjwTL0vYcpMGtnQt1wH3oFr63Ga1J4XpHDbvsOH45ndFbypNZ8YJTz6lTkyx7PAtMyYUoudIjaAEk51ZMErEuDdZN/GlTg1QZZWbjNgdyoQshkEx6UAm4g8T03zI1mIQpRw27JTqxlUeB+Y7lcHDYGDDu//NBLwObGyIKfa72vW8hHACO0MKostp77OPm0LJg64jOI3hrpoyQ0wl0GOYzZd4Flxe7kb8vBYdwSLbZQWIGkeyd2VLMcqgxFKSwxzOpBppd1ckFGmZNuOKGV8MA9VPfdcA3xiNj1M/K1KrwOKUCH7EKAewK2DjEDuWP4Yke8oQqWlrx8x6T5EV6pch3lP+ddI1jnOxVCx+yTOxbsgYT7IB6hq6bE8fBbtAfg5miDYWGmbPXYDFHM88DloJBg7SvgelIaxHGhCKK8Z0z+OCuOTa1Xgd1CjgtN3lkyElucuWLc4002QaKvxf42+EGIg6bKR9WVyRNNYlmw8XuWt0th3GKuvKUXzaaO+gUBTI61R912MfYw9+oCp+oA1Biz9NqYI6BTPOwcfn+rTSbuTfjbiqPO1Q8X3ALSOZI0yb5SnFS3Oi3zMo6vkEoCuEwiUIYGtDC9ryLBi8vKjytac1N98hGgqqMw5GpAjPDlt9O64EeQqE4t8siY/TTRA867KUgBNXYRAYzQPsl87iAP+cBovgXjeVBKqZnsej+
  template:
    metadata:
      creationTimestamp: null
      name: node-app-secret
      namespace: default

