replicaCount: 1
app:
    name: wf-api
    version: 0.1.1
    description: 'A Helm chart for Kubernetes'
    keywords: [helm, chart, kubernetes]
    namespace: int
    dns_resolver: 10.43.0.10
    primary_dns_resolver: 10.43.0.10
    secondary_dns_resolver: 10.43.0.10
    dns_resolver_port: 53
    api_url: 'https://api.int.diycdn.org/api'
    redis_host: redis-service.int.svc.cluster.local
    target_env: int
    target_type: api
    front_url: 'https://front.int.diycdn.org'
    sync_data_onload: false
secure_env_file: AgADaJEhqf/Vd4FrPlWhc9ZQVB3rzHOed4bQ+sgeB3uU5fov5ZC4Wsx1Yd87lHJZzf4j2Bpa7+5jth2N8WpqwrVcc8JLqtObDiUhWef/LUCVWnsYs0lyZ0b3Ic8FSMH4tOS8v9N8FbdXv1sqNLu4w+4Wt12Aj731tObgl3oZ0vc8DLRoxeKtX3fyOdNIDwc3Wa1SN51urb7TLahhS4tmj9IajSCKDEU9BEUw9PRP8VGScbdvmfeJIJ9zUId8RK61YFAvtnXhvP/lcq8RkGKLL+kncO4d91P6c+3hlI4nvSNQrgb6pn7HQ7xUQ+R7AtEC7ZNSV+Lsz/ChuRTzd9mcrKKNvvrNJN9dwT91ngBRJgP2i8ZrKupPrksXJajps8k9nlkPtXfrGf6QehyhU1AIWZ65wg7rEdPu3Aipr2xyvK7PPKAxNUakRPL3ImKiFBJQkW9ZXWhtQE/DjHUXds85R1oqH4X9aWQy4d8LxGRwGEbv44zemlVCIeGkaz9WKq7TiD9M7igMxFnSz/vyumoGNtjMfkklzmRDjHDlILKnYAfYnyFnPscm33fTIzdfJgQe3lSgHitmDWf99J4srltfS5oRyAisWYuE7G+08MFMl0M1fXBUPcbcOcleoS2OKf3ToSh1py1+0n8BsRrEnzEO/tB119Sp9DsmB9k0mOWJTJesuebKJ1rLnKwpRQSulge7CjEMTsQ24xd0nEyjIeIddc2rZK1qx/5ei+O9gnCGAwtBVWuWf2blPTEpKMD0UokVG9iA4U/nBfwQzRDUoArf6GEpPe8459DK9p81ZiXrZmwsmMo/uMZ5I2XVSohPudZDxFuHa+ABLwIrRx8djevyT5B5jHfegmsVQPGeOB0FLpkSkDUbkwausGwiDmNPU7Ks1nFH5u7HbimwP5B0qFqRebhZqNBXG7By/AK3807nZvm1SvL4yCsSRhLMAmqj4IKqUmED7DoLOOTflWdgsrFm7HsivaPKnrnrjo+/JXumlAPGEjaAX8yPIbDqzOlO3eC/KukZvwTY3ZWaOhf633oQtrq7Uuxwrqd4eI/DWzI0IrviNrW+vARcSETu3u/p7kPJjDv89PwzXBu5TlXJOZz0yqKBI3SZn8wA4TNcg2iQTAL1x91Ba4YwMvdUWRT9QQ1uae4JJf4MsmvLxYNXOsFxQ1tuNv3ODQ4r3wcZmClFBl0CetZSbtg6DSRkzRx32ahfIYmHZG6ZvCk0tFTfOV+aSlGbgGTxj6TwlFnwIVZZ9wTRQgB7SnyRbkPM
image:
    repository: bwalia/whitefalcon
    pullPolicy: Always
    tag: latest
imagePullSecrets: {  }
nameOverride: ''
fullnameOverride: ''
serviceAccount:
    create: true
    annotations: {  }
    name: ''
podAnnotations: {  }
podSecurityContext: {  }
securityContext: {  }
service:
    type: ClusterIP
    port: 8080
storage:
    enabled: false
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: ''
ingress:
    enabled: true
    className: traefik
    annotations: { cert-manager.io/cluster-issuer: letsencrypt-production, kubernetes.io/ingress.class: traefik }
    hosts: [{ host: api.int.diycdn.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-api-svc-int, servicePort: 8080 }] }]
    tls: [{ secretName: api-int-tls-secret, hosts: [api.int.diycdn.org] }]
resources: {  }
autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
nodeSelector: {  }
tolerations: {  }
affinity: {  }
