replicaCount: 1
app:
  name: wf-front
  version: 0.1.1
  description: "A Helm chart for Kubernetes"
  keywords: [helm, chart, kubernetes]
  namespace: int
  dns_resolver: 10.43.0.10
  primary_dns_resolver: 10.43.0.10
  secondary_dns_resolver: 10.43.0.10
  dns_resolver_port: 53
  api_url: "https://int-api-controlplane.brahmstra.org/api"
  redis_host: redis-service.int.svc.cluster.local
  target_env: int
  target_type: front
  front_url: "https://int-frontdoor.brahmstra.org"
  sync_data_onload: false
secure_env_file: AgCcR5kO+kIGsMd7bmlw38ZIDSyWEjl89c+CppgKidG4jWC+nGaHYUBMPCKZQwfymI9C2oghtP2OHp888R6qsDU1erviVVSB6kI50voa7Dd4RkZYMDEnB77nXLkonDzCCkbmhhDpo6MwxR6U4dC9qKo/Qi5BYnxr1xY5rqyB0GWxHsBiFzmM2k8sPVXENVIr3RvCwmxv6/d7N6n7mQBkoUZ58dnT+ehw3PuNJpoSvf7VRWpGranQ2tnRJlT8PYI8GK4XKMSwtaF0peMawt4MG5UOt58zCiT/RQRttGEo7rS6NdqSazxwcRJTWyITI89StBO/dBm+CK4WorOMRq7WGPq18tPbIoLcwkNSNemulCtRG+HCWtNPeaWybbo3J/5WePY3ajwqlaCsjyYdX+dWB+/QsevwYbQjyEo78ahfeCsI6tBhyfngPZiS+pbRHApzHcYqM7PDR5fnpvoCQWY7RmM09DXnEmRQQ6awW5Qrvyzze/z88wVfvE/5rNXg1Y849p9E2wVDQHjO6w634R94MJg2yAVUqry0vjU/+QjeB8+ES6SzXj9Nw4qpJCHQOmTxBajlkYeQMvBBLqD3XlfeKMjmE2ulpLUIrxHos8zU9+wo9eM6Ta11xuq2wopZMhvAqDQY2+Uw5KDoRO3kZAcGn28LV+VVgihx/u8XS0Oxd5dI91XKfGeLjJFVuwKhC8ywXKk3a+FgjqHp4xV8n+OZXWEJyRVb9Wn9TsbdRCn7d57gp8StWjdjt82Uf+aaQdNBPGB21CQjztdnN+d+FjwSKYwGQ5YlnqqCAet05oyM242BahnMzDMBIbB8a79b607KmA1VviuUi5KipORqxo/AoTKGbbADSeDSTGxglnkh6qQUJGUlu57mKafhOm6yyMt8Hign2iAAZcJ6htWT5O3XsWtqyEP7vUpWPbEjZaKyprieSIic5oqmBQiy/L9jJHXtsQpY9inrbnG/gjO85c8KxlYIV74jLVaTpx92qL7XbanUhg3zLCjRn9KO/NNabNoUEiQSe/rZch9YJjhZog8z82/YRPIm2dO1+A4hCW5SXng0v33T2y+2XlBw/GSQCe7rFTDbayCfKCyI52LMztXxF4Xn4iGKWtIueSdjD7C3GM9r+gc/jaSAGGKondi/dg0V5uqj3BY7wXIkAUn6UoK3nMNde3CmcvqUVxfG/hX9LgxOkDB+1W1c+RQrliObIfBUz8LOWeUrxYKuDEqJsnkmxfzJPx6vg0eHR1TRxalnj9nmS+TwxSUhxSYgaxVQq+s8ALf8/k+0Ken732KxrB145HR7CVoMjk6spicvJpeNxbDNnTQ1lAbYH9bYDFz21W4Y9D228nFtIGaCemp3DcAk6H/vNtD+Aav6XuBAxhPoWlETVDL7i4FT4DwjXFHKQfebSlhtJujQiNgZY+hcETvh6/mRgNfhC8DY1VMGxXYczbmJUHobZM4NcAjPvOg1KvsWuGPZLhr0XYOcmwOpI5RbyEjWVof+gTsuv5vOqN/Pe7PvvEcXQxbjCoIGjuE5TUgbMN2vvv8hdNpTTvbt8C1YCw6vtO9kLCm5s0mvzkpuoTu2Ma/VuY8dtd9Frw==
settings_sec_env_file: AgCE7evmFoBszzaZida2MYXB9jCvoIBRWnJOWK7Ey3CvGetnQSDBAqZelnl558JFP6G3XuBa/2ASEGSEM7UQOu8HpDK5dr3x/9OvhCsJPjhgY2iA3ED6j2mADlpLHkUcLp0ANnpYeM3uq567evAr3WFd0cMHl8ubzT4HN2XPD54JBGTn09j35rqQgROjCdbzajpeKQrfdPZKjwZF7aQJTbWf86ogpfHHA1mXv/myGsGFulHws3n0EnxpT59OLawWnG3mjydLe3bcgyGtKXY46BXhgidMLAXbAvleHjTNVuBEC50c5DZdS8YQ0Hk9kSv15hRV8+tqO2CuMKf6feYt5kR7akhJTM4tYxl/A8MxfUQR+NgwzZKD+Dr+XwKG82Jeez5Ysu83VslL2mfh4hgKeaDIFDlIouDrBKEgmkRQo/7hO2dRho5YUfTTLAbdiyq6abEdRDpg2cXrZJBd2uTSldQKEuKf2AwBekUGw/01yCJsEqzAPLuLlvdPkbdf/nl6f8fAXgynS///qz7QmtNaVG/xxLti6mvYkJZdpkZ5Eny8EFC1BuJxPwzTnC25EWYeb2T0cfZ3aVEu7MlrRBEUMytXXBeDFxLU6g6AXhKMwsndvs+5UlWPEWi8vLaYpuWwjri2K8qvgDXCsQ214NxX8RqfgQQyfoHSQQdTI90TjTWeREBRM/d/fZ4sO7iEDOwh9EJbbJJel36WkNdK0TA74qu4cvk1+98H3YvB/NNYelcWM4HWRYcm4tdAb8Twnv0iMxIbzJyhrz7xB4JKF7SVbwIRbo3KiK+dVFHO6OHA51TafZH0S1b9TGoz8FjzcdQSQ0Vfv9nVWE7GcdacT2/HG5hB0wTrlW/qR5s4dC3S5E/go5mZbU5ymyqfMVpr+SUcrBFCWeM359zR0k2r33OKJ5zF9soVcOP4Z/5f2ByCdMUlcG5wG+ZstwwNDWp34VmRECpfLWGDpXXHm1ktxlgKb4qNNd0LzsqgN5J4OIsryi1Mx6IyJj3+VJviLDWgNdckSIfGzvbnYJ7yxBqoYONywEUeFJDS7o88cVSGzSuKZWwhxycJEk23SLYmqyHm7E4QdIWg7G6rtJppgk6gdX2FXuJGtvb1tydtvCwv+DbyBrR8cSpdRVWFSKYt7CpnkjN9M8Nq6jzgO3qrwU8ugJbdAR9GpeszqSoZ0dX/oNxy897XMJRA9CX3XamUyWuPvb+BBiOUclX81Ez1wDOtMbu6wWj5KeYkyUePkn3DJkFUOpb7mYYlBVtItn6RxX3jivNmWsju3Rz3o32Qr6XxMlZOHuiAvNdEZvCc2lqeMszdu8MKRAFlq3wbRrNFoaDtsZFJiHkke1eBqAaBgUx/wHQf/FtceSsxZd4T/ob6v9f+hNMKXiXbx7nmfz8z+5NRmUFM/Du5NCetEwbC6rDJKH9i/q3KsZzAzelIhMV5MFKcVAWWk1bHaSAQd9Bm1hUgf9SAHLsuaB1zp1MYJ2N0udV44Z7zy8avdkPjDQNiwZeYfqDj3VhHeNVI9MKrPBh6kPjhpaFJyO9MeAV9pcKa4iGdyFJyhJD/io23ujKy4VVh0t2aD0Mmhn1U0nLRfIMQDvX4oSNypUSxGq4bTAGsP9vrjFjI7IKTsWopGkzycccrwXziL9ceW21FNbq7Woqae8CSzMScRRSD1KdUQ9jpwKmr8hPQ6tHA15GeE0UMR0pLTzEheKCMczk3hHkPlmVQQfbLtkUw2J3R4BYFPpgdgqVlm+5gm0cZIDmdfiFk0akEOhYqS6xdljk3DcjtFDZWUETV5eo0ZwiOrCdkQF5qIju8+YJGYFab9gsOon9OU55dvSdAAt8It2pt6a1mhw15VGhSCRZJ1qlsvvI1QWzSdkGkBaIOG1854NwspgE+l143DJiA2oDqlzwRLjBeeyzi3VxFE3XKvR3wS5nPoQLIQ7UbJpJ9YXW2rDHgTtjzlApNR7xNSEpLHieLs2JRy1MMZibYCNBzHS3YeKoHgKo+qtugMYVrj8hIG9YB1Ch/nvtxRiZAmHPsnfXJ6B2773ANHGSQ8uuT37VReebay5aGsphIJroRyZ+bF4Pn1psbhf9i5KX1vu5jC2bpLDZQyeVSQa8giOgyStqCq9vNWypW5NkhzFnhlbDIwLpoNntBhVt5trGfAoZBEf5ToccqyZGXv2ycAypgypAOVEbKv2xgboPBPX5Qiq/6Kt9BAQDC7WM+/JOiPYUjrThsqfWm0w9h2vRsXU68QKo/KahAlic/88xtL/nuifVhsPe5uzP4TVqJMSNNC+nHLLqBPeT7xLEqtkc++VEQC0I7dMKhgahMVtKcXRPdRXTb1IxUD0hrGh6ft5xv3q/WpI7KOolnbmanQeIUYeo+8vBV+joqiwdKrlH1XzIpU6zTiO1udtuyMRGJD5qNhGNIIl1YsaqyvO1f9Ua5GQCL6wOmuRNJHVV8m0lJmOAVwlLP/CjWSVl/3dYM7QcdVCMfU18DV0vZj27BH+EtO0usJ4FqiWpxFibuU3uFXNNfrkYvK8crdbOL59pth8HbBX5NCPnA1Jhx4vRvMPqj1snk3msJeH++G88Y1kjhPQR5Alg0eMODRh4xpIoPxOmfZ5QhRIr2w6Kt1lpuv+RZvOuYMeUkhuLL6ilhQ/7Nwizx8SB8LmsmmEKDvR2grH6LzGcfxiFFauCUbx7sJZWo0lim6LD/Jgw5mt4Qn9wfb7Zp9vM+Hf9vNDdTWB4Ax/B4oweIZklpZj55QdQ3MjBpjnZMiopGRqHxxzlS1vyhTM4JkfccOLa4thwfi5/izbWhfotqksEOZp5Drv6sVWRUEVCujhLEeVoJBwSpOMlf8R5nobwScFo1ZFbhmfxB7Aq33NakaPqYAh0lfL8Vwuk4ZymEn7NAeL3ZqLIrPgl4V2GtPrC4qQ6W9UmG/jJ4UJ3TTwf591RR6RpKURts15gJQMe6HaKvaSaNsyd8CWCcKSZOAEcWXEgYPbvnWLFfdHm6jv2uiw0AqEHHe5+Egl1/8OcOnGACF+gzKKyfuEKUB6B4ccnzxU918cLgEBF6aLH6I1tY50c5BUBYGmH2qch3Y4G2sVQq9kJA9Rc9X8UTVJC4KdCwFb6SV4121mra3f5Rp5mAkA8vfSI3+84IaYgY8YGUcgIxJgG3svwEe0pUOh1yOyQm2vLAW32ypxHvyWa3O0lxB9YDDQZyoKQZDd+VP9ZdmGh84QC52D8wg7BiGu0t2WIvfEbTlU7hDdBsvC83zz9Gmz9nnlRXWhK9+rWJLt7FlqoAEqknKnNvNZLKShXwH8/L0Dl8fTatnqA7UBIHFCtpTUTif+G4/fkRwMw3CsQeD+VOAfWwvrBFNkgrVhnfYhEvClHVSpCmpZQkMxb8ZjEvtoufCGQeEVLSicrC/1fZ8Ke/qUvI0VI/pzs25xAOmXOBYZiq1EMF5d6S6aR/76c0GMQ9llaM91eLhak6UF99aF8gE6iup+XYuDrBd3GpkzDxqz819+xTcGKeeZsT4HDSqlc9NcOSRpcX+yB5ViPYgDOWu1Fds+I1PNfWM5E7nvAX54ghFmaP7d7NekAE+NhgBofICLxhLBk2pxtK2JPcPGYttyM9fAEysAqsjkvpqCwJ9erCyMSkgUOCeJCD3Dst1mVdepgF2h+Dgo4Icmb/HILBL7adActg39VNC9zyHggyrC5jWSUEp8M8UofGWGww5TeCNwgJPI51y9RnkwMW5RVU2GP0SGzJfULvf/2mBGpceLlpQnYOF4orA0CKuGZ2uLg/88aaCnAtuQoOx+pN1fJGChE6CWdAnP460dfIOpr2pR/MvevaCGFgYC32ogHcs1pESG5Ck6TdCR2KSC8StZUHbVKHjeU/ycy311f7cqiEhp4lgtTFP4dMRalcldjjdnBj1G6SVJFZ/F0Q+eaeICYNIzd+VHMvIvgvj8mCn/WuR6uqgGSZUCTxLBXvpSAc1Oxi7YIuFUVX33AUGdtnzgHx43JPfTYTxTj3W7UhTowjvvg5Uvjnbp7TuQya9ROKBsY2aLdGh2Wj4Ot2mCnes4N82mM7tUNu+3ctlz8g3OfvrYBzN9HZFXbXzTjdvHlSZy+/oyk3tUil2vrUfWqglWQuLwxuzSnNo62993tsPtW1cTWv4jXHMR6VOcqMPKfjzd2ZfA/XQDCSb9CeVPwoUA3sEiobULfpnyz0rbYDoh+2TjuqMOs8qnst3bicdNcdVfKnoK/k7tZHmrp/jc2naVRVGHM2xzcxfAcnS5wL6g26BiLoVDR2hp3EAmPOGa7vG6oM94s2j9ngxBwK3vX3dSTrV93WH8zSi5uqGICXx3/KvUMs5vwMFBNpRPsGHxuBUbOqPrWhiTRXaPQA0J+jnOJa1rAPUGfomQGuZaZ1AL2TvL8xc53Fu1CxGjilo1yLxf36QfxoPz7wPq4B/65oHib9IOk0dF07wCqqD+sNJ/oeyL6T3ahfdBPCO0YN1XLfjEsRm0+od7aPOp5d9UouBwjqLm8xAzUM5/jJcjp8xW7DMII2a02hM9PIaziNR4DXWZPHRHPBLtL0rNe7eHeozUElJmzcRrdKR2d0+I9zI36n/ljlv2iI5Ob4igsSbb/e6YOmwWVseqqyo19TeMAXh2seTkctT1fF1RGHASSTqmpQh7JFTx78MPcr2yONsrmXJBLBzAJPO1LMw4zFfP0C0FFGruDdV+n93LJqQondQ2ItPvu1x4ttTH/qycIh5ah/MuZCsrlzQ2dQPtDmfg5wf2vtohkVYL4JESkaz6iszfLF6s74NyhlzUI0lHr/OMmmv5goirrlnhxuU7ZoSqxPTyWDSeo6U5kbTV597GZPdZcY0IlaIfGR0DSKDqjhQnCSZ52jeNPXoTpgn9s163OnLbHLbsiGMDJx4Du5e0Pt3CShu2biJp1Mu7PHB9AZzPj/M96b4Pm4JHDYy6Rz3Ze4kwWM8fmva0yvWlicVaT7RVTR165yLK18vMO7jmUhVoMz0gY+mYAMQWsFxWhv4wegyi/J9mhWaXlTG8F13U1f+7iOXNStAg8PoCPTmhNv8v+z48//gMelZnarXetsWKwXT9HsfUktOa3B6Mp5Xnsnd0pnd3xK639av8oHGVHw76yQd4nMdnWBWfIsFICS9fOlyKm95dVpsvgZ8VPajYvqfUIIpPUX6yt4c0K/J5eENMCC3UPHbI+VcEgSYcioSsjtJnGyfMSuYcQWZTCFqviKCuCnT/eOlfq3ElnQHj5aRbHrUsCVkPB7wQYzQCyfnfJYUVNaq8JyvoWERMklcb1DNLRhQVIHGU6VI4+xpbwoveZuZoykQv5C/JSNylXZQNKXtoSbKx0zJ4Zfdfx08RHyUTJQiqxcu/8VIYgH+6nQw2FGHO7lY0/sJ7k9A0IWuKpyn31wALSb54m1/ZKQTHs3rFDlKxXNe/1aaxf4aYBcykZFnibU1yJcBCC8s0HGh/OpjJFjLu70IW93YrE20R3GrhxyaL8Sg5L0m8Q3eDY6ly+KtcebsLg9AzRH4ojppyhR28R5bso619OrmBPG8Z/iBLX33R/m1rlsmBC01OG8vrpyAeQDKJXMdxMG6FZRxrqmja6HJONMwxsLtNz9hjZHgdEHztafOHqUFsapZ8SI0kzXc+Hw9jHgA9lX7Pft0m54FYM/8KXK0ut3Qb1roZWlEMbwsJkeJ+2m1IqXBJuL5/sXsei2iq+ljb9KMzKD58P8hkUVe2EMVNr7meVgQ5XpJxKtyWOV2pfEB8tRio0jucr+eZ0WCgqzwQY+U9I8AXah+2jOu+TMEmKhZ+AHv5eEaTkZ5Jwmm70zmoHlFM5m/pepqON5jMnXQv/IkC3OqisPTHTxs+Lp//EE4Nc5hqGMnMHlB+viahRUY6w0sLVKMn09u0bpKJEHCS4a1S6E06uAj1eNYk20HLGQJVQj38/8ZLX/FkRihYlHOFRMlg1YBN9JypufWPrHjJeyugx0ySAS3FV9Oiu6emxZ2NWk8cWlYZrc+mqKTx527J7v3Xscd92Vug00zowtUdKeS02YRhgNUnUUs2iAb4t9p1eKIpWmSem+eacaBzrpif6LXuMg7QSZ/RTsvVZlbGe4N8RDVt2sxyM4fq8sX/yEKDNMlK+XFcvK2lYlCsXgK1/h1VbcxruVyOm7XYD3VritfsiOG+ALSHvMz4bDFvMruAwEPtVBIkKUWZIKRGSDwVM1JPY0HYNlJ3hYoEMAXKtGnPKkgbqnQCHyZt6C00lgRo7bN0+AXMGX/cycxDG3A3MvYe3m/BOnE20XosTDBfGxpg+Tpai/z1d02M1Gycj0ztvPK1y9+SglVdcLn6Myil3PAI0xE5N2aom7Mv4yFlzS5oHcT11wdK5jtAGWqd5jtlmQEoa6D6S4U5g2K8g8PEWf5tPOcJJ3vnasjIYF3J1eiV+IBk64eecpHV9KpAmYu+j8q0z0unF6AvCrrsnYteVgYLuEVoAncqbNlkADK+NxNfBMM0MSCfrlBjm6Iu/JCfiAWRlglVMdqYwKm/wWkWytlIcPlZ8pH6UIg89ttwiZw2+NumqNsZg7cLjAC4fOIqrtCnkV3BFC/3OP3lAPbIWiehMTaWfHe4qykM8S7RWUwReU8+/ZzA38jsBniwF/Hbg0rg+m02JPYqEpDoBDtcc1jWUXIBIiGyWtoVEljutw34kqYPlhsbbIOMrld2hwld+uGVY9AI7dLPAi6+pvdC7EfvAyKbr6mN6F4qM1wx3PIiSVu8+gW/p+aaQvwSZ26bpHAOAYcG830QQPY0XnzMCwh1aO4t5xpTyYRybYMKaA5iz+0zwj3uBdAobIIoLykEj3IsRB05Jihl0M2YOUW3mYyumb6swrktoU5/zivtXWpCsGPI604UPJheZCOAQS5pTxdiUGoI1HE5z4+5uOS77JkOOup/ISu7G1CIOJ51JXHz6xVswI7TjErZIjqiXH6NTxDcpSwgaAYBJf4EelhnbzYWx/hCw8aNBjdcN3gD1MkpuE+zehYnSFgTAGlMeLBdeCfj3i2VZGsEUo7jyDTqOQd5V3gtxJeeRtrNDGxMe/tuOtdT0ml3KSFTMA2fPd6RtfFudjPAJAzQcPAaE2OFh8aA17C1WSAuV3cQklQDwLgp7uiMOz8PA/Mdp75NS3HBM+MNEuwLdA2cenDk+aM8EGUhsx7aC+P8gKBuSi6Z/Yw3p2sJjWKk6pHuKlDKyDwGuG56dmNPVA1tsXn29Jig777lV4QsD26CaSJJmNpFJKutxk/FKcjWsQErsnFO4nnR9Shw+5AY656X+9HcsgFGMeDFZcf/xLL4YR4Cc5gkg8NBmMZjExHJ1fIsq+z80w/3Oq9pr4IfATRG5HxSc60Jfl9B4EeODZpoA2JI4SK+JcRF8NFryI/tmwd08DEn51XkEbgBx9aaSTzoG5YRkyKYgS2AtFv/Pr3g0yeA7LPoiMFtO5NRpd9C5ULo9J3Qd/8mO5eqw/R3PWy4QAxQJCFm4Hr9gjG2ZH/S5etKWku4ABgukoIALA1dRAHeVBwff4znQTlz/hQDKjDV58jQ0NjlS0zs7HYWlJDNThitnBUxgFMCHqYmezzU9F3IcmGqWCywJ8JA5NLq4hOgTulK5gyGM5aRxSp0UWz5HPpF0c7QdPJqYG3Ga7HDulz0EcCxyGcoQpyX7ZEk6JrLuOvTm2nFA2MC7689KQHfRufEJ/8am0RhdlIRgl6MpEKw/VoIn8HivYxdMjcCvp/xeYPS2djou1dzeWtZUitgzvsSab9e9DP9btigmirJxc7OHXzHGSYmze/2mkPF9z8oD0RgiH/Wq7tFSqK+RnbUIbVJ4+Ps6O8LDqDZnd37cXf+DBtUJdTQra+FWH4sEXj1mz5idAGWdEF8lP9tp5L9tNCSLSq97ciZ2joIk9dkZNBn0ciohDAbvgB59fKLuvAd7fb9xtnn5XccXRfCUCYyow7OQm8Q0D8D9ERv/slq7y5BnkdbEOKAowZC6kS9KcSz0ZmrLl3FGP/Z7J7UgRNWIuXtaWWPCdleIYxufIzFL7zBvMr4cSpYgrnhQ2VG/Drxflpio4vyJ+vIi7cCk2uHa23DgtXrc4N6pd5mLsXpv8/NGCrJ7tkqX6nhIs8aC8sk+a2tBaMEEN5aj42VPYcsSFFWA9yHwINUsGdLdTuTA4BhCzOasHOALnFg+c5HaWkzLMQym44gmKLS3gDQx9BuiJinalPA/6PPk4RHi2ttaJqy1mNX/0O6NTe3PvWhA3zFMkIYBNte3VwWSIt6GcI20Die+sIv2TNN8pHlzFL4eIxD+EzibvoaPdiSjYdAPHArn8v3HfNJy5WMKKHSVQW8jVHKfK2f+TZR7pVJMy7wi9slf9OMoIblg8j+4Jl9UVIF8CThsSZMsO/ZRlJAaXGj8DtLmdjbX2LjarG45eqXsknjODhF1ovhyZW5IMjyw3vj1e+wVPguvlvNkDOiT21iW7DI7/bQ/TX00Tpt2Jy52dSxQyDVBPm9qfev2yDAnuKUxZkY4tRrmVhTytQLzorF+Rh6hcWnNaUjXUpcaJZHZMwqqpC1x8HZlYHsmhAy4eCLc3qVLS7kZPFkTGXOsSB8hKiYr6d2WcXtGVcsK5n9OJ3LDJNQBTx2C18cWe0KwROzeuBsIwelZZbKR2ao+QZOUi9reRHBu2UJ1FqnOy8sHOGNtIvXQdOKewfPCJnbbPuzaz1uqOWxhvgU5M+LcKq54U6hCpK6RmN/FHRXIPeUh4zCR0rT0f8kS2fRWU0suQpL3OpE6Mknc1Ls+Z2zu9PkkWvLKdeBAUbnuT9C2q6kQpsMPMiQDMqU2JOOG30LoM99awpWlBdYYvuCHd+LdRukIqhtcxisbqfZ74HO35OViGFXC4aTsXK5iJPWo0mYp2uZreTBkicryEKI0JztsIlXyZm8Gu2VmLQffypUJVP8V67Oy0ujMnVjlCg7tA/0Ayj5hkdRHmd55s8nYIFnrgv0v/b3JeZMdfILkB7Jho1ypTpml1klu71meHSDkbaihIi4LAFhh9Fqvof1V3GuxRthT7btrJpwq80wh+jn4AkgpyHcAbh/5dV17/BKVGfu1oHQFd8b+JYz2r0ycoXGatMe/R1Zw2JiaknobyZRX8NsqgF3SSmD6hjrTUqAwCI1QvVLo3ETI7T3E7N+snILkOcgQQe0SGUBonH5WmrRoZ1cXcKsmJJfpkyNwkckLbhJYOB6T8MWJFKSWDq3zIFiR2dyy1KeJVXwK7fBE7eYhoLiji8sgYGh8ZB0RcBBxcf5ATYx6Ad543ABEXkHTn757W+Mcj6DedO2aGM8ftai8MsAsq0d6OWadjpM5RrUc6udE32xBlq+lHzO/lwA2eFU7PiznMfAdVuiDwu+JKg9VAXLC0Y/ZAFDQeHfdtj0k89iNF5Z8+mDsR6Yh7FEozm69Ezz8ZqQEMjA1yTXKe
image:
  repository: bwalia/wslproxy
  pullPolicy: Always
  tag: latest
imagePullSecrets: {}
nameOverride: ""
fullnameOverride: ""
storage:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: nginx
  annotations:
    {
      cert-manager.io/cluster-issuer: letsencrypt-production,
      kubernetes.io/ingress.class: nginx,
    }
  hosts:
    [
      {
        host: int-frontdoor.brahmstra.org,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: int.brahmstra.org,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: qa.int.brahmstra.org,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: www.int.workstationcrm.com,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: int.workstation.co.uk,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: int.odincm.com,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
      {
        host: nodeapp.int.brahmstra.org,
        paths:
          [
            {
              path: /,
              pathType: ImplementationSpecific,
              serviceName: wf-front-svc-int,
              servicePort: 80,
            },
          ],
      },
    ]
  # tls: [{ secretName: nodeapp-int-tls-secret, hosts: [nodeapp.int.brahmstra.org] }, { secretName: odincm-int-tls-secret, hosts: [int.odincm.com] }, { secretName: wsw-int-tls-secret, hosts: [int.workstation.co.uk] }, { secretName: wsl-int-tls-secret, hosts: [www.int.workstationcrm.com] }, { secretName: wf-qa-int-tls-secret, hosts: [qa.int.brahmstra.org] }, { secretName: wf-int-tls-secret, hosts: [int.brahmstra.org] }, { secretName: wf-front-int-tls-secret, hosts: [front-int.brahmstra.org] }]
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: {}
affinity: {}
