replicaCount: 1
app:
    name: wf-front
    version: 0.1.1
    description: 'A Helm chart for Kubernetes'
    keywords: [helm, chart, kubernetes]
    namespace: dev
    dns_resolver: 10.43.0.10
    primary_dns_resolver: 10.43.0.10
    secondary_dns_resolver: 10.43.0.10
    dns_resolver_port: 53
    api_url: 'https://api.dev.brahmstra.org/api'
    redis_host: redis-service.dev.svc.cluster.local
    target_env: dev
    target_type: front
    front_url: 'https://front.dev.brahmstra.org'
    sync_data_onload: false
secure_env_file: AgBit2dTUF9ZfnpV+I57fqEZkf5sMyI9M5Vk2jt76p8KYAtQ7Qy2XmYbVaLcK2PRcOwunuBAQb1G3dvHScMBmR1IyxjaYNnM8EroWHyHEIuw5UZNzbxWg+5kLGe9n5MWdsi8kY8+iQRL09JEtK/VeJlvzPJjCQyF1pO4z16NAEiIs/vxvPbDjENqpktm+H4t7g/Ymg3rBSvCZXvjp0G0F51hOgVpk17rFG7BkeiDp+YcZFaLD7cX5uSe8J+qOiki4yAyxl6Xl7nSI44pNntzKKtDUcZqMwDJXgnK7tmjZu7LZKyjRCqyu6dDcEVIgdThyujndy9JQ+SNeShMSxGc7x848hY4ziXzULAkyRGnH3FDvv5DGOZLTzjgU5qqTrHFZenybuK8VCJxbub6WmhU4/rBhQKTRe0FTIQWS8xRgsho0O3dALmmxOeF9wppAcR9luzk0JwJu2j3CTUI1hLrth37kmC2YIb26wJp3HnrVdMS5dYCuPg54foLPI5AVIqxoCABG5ZqF2SDyXFV0FEb8g3Hyu95i95907jcU8qQYP3Dzb5xlK0jqkddxBLNaKOdO4MJ0h9pdKuqSW0zvxipRc+/YogWehIY2Vn8ErtZce5g2Jz/yDrwKIEbuwkEpWYjVMLFNOVQcckIaTiywRzO9X/GEXhNQzIh2UXZTZbmGiBFAewb1w+gWhrTlWN3GpyKZhAXjHCMeR7yiS+N4JNAYPCbi5jYOmBimiWeWze91xSXWLVUcde3AHNAWP6dL+sDiBwaSppZTn+Xrwltxy6HPslIVMgwbLx7AZ5LRx+Wz80SyYXxzB4O9Qqjp6t2iCVgyMu9AHeCVIFJQyGUji7M8GK4x9v0KUmdb8ncjjLZfFL2VbOwX58O1sOs4F1s2qqUGwCpsq0RN7W2PHdlplWw8JVbCmZwKZ+8HHfoym3OnC1xIKTOf0x6qAT3UmL8IpZjTtkh5U52eWcf0tz25AiDYMhaFMau/ByDc8e/s7X0ZduULvdDoVJPzFcjLHkpsVGpdrE11OQXmm4H2P3bMAb8MKE3j2u2o26mLmdhItfylE7NCMIPeQ02WKLPXht4N539HR/1Mft4+xgHIviHHmfiTo4/07ELySoPLYEqIajS1xU9bmHa4jrvcOevOLob833WSysFo9BsGD1Jt+hgvRW7Nr4XJf93wXV2MTDo7Ge43OfjZ3z30v/+gWIVcIckzextQfYwcJEbkVresYZjs5bPkYtMylDoik+S2ZSyYNiKVgjV7byn
image:
    repository: bwalia/whitefalcon
    pullPolicy: Always
    tag: latest
imagePullSecrets: {  }
nameOverride: ''
fullnameOverride: ''
serviceAccount:
    create: true
    annotations: {  }
    name: ''
podAnnotations: {  }
podSecurityContext: {  }
securityContext: {  }
service:
    type: ClusterIP
    port: 80
ingress:
    enabled: true
    className: traefik
    annotations: {  }
    hosts: [{ host: dev2.brahmstra.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-dev, servicePort: 80 }] }, { host: front.dev2.brahmstra.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-dev, servicePort: 80 }] }, { host: front-dev.brahmstra.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-dev, servicePort: 80 }] }, { host: qa.dev.brahmstra.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-dev, servicePort: 80 }] }, { host: nodeappdev.brahmstra.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-dev, servicePort: 80 }] }]
    tls: {  }
resources: {  }
autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
nodeSelector: {  }
tolerations: {  }
affinity: {  }
