replicaCount: 1
app:
    name: wf-front
    version: 0.1.1
    description: 'A Helm chart for Kubernetes'
    keywords: [helm, chart, kubernetes]
    namespace: int
    dns_resolver: 10.43.0.10
    primary_dns_resolver: 10.43.0.10
    secondary_dns_resolver: 10.43.0.10
    dns_resolver_port: 53
    api_url: 'https://api.int.diycdn.org/api'
    redis_host: redis-service.int.svc.cluster.local
    target_env: int
    target_type: front
    front_url: 'https://front.int.diycdn.org'
    sync_data_onload: false
secure_env_file: AgB8jvPnRGQMgb+ycYZTCSC5puTpjMa8+AZobLY7OFY8NTQsO5NlDLyKPxHdnTC7fK9RSiAASEMnAkzKeKIU2rm2OfmtQhukH6sgYGDW8FmTaczMsSUUg5YB+Gv4pnM6d6CGOM+dpj/Vkih5e6+m+qBSbEtNi8vE7EkP6WWYARlmSfhz3PhkwsG5u+YgHOiDd7VWQEAyVdznP/t1OX4SDSl1Y2i0fDMzQfV2otb4FKkBrrPtqjpPkoGEgJwxtncuFyT98S8EEqbDBFLQYuYyGqjZQ7GUxSCEpmuVWLJ8x4mS9m9DTqQt/fUoQriM1LSL3a90hxpy6ItgfSe7Hen2LMwsVkf6YobF5o6jQdd4z5Xw4FX4SAvzEMDX+xSWRCrySUhaxJ3chHXyljXBEwKTYDX/DzSH00NW5IAfnTcYbYK6yyKiPMGg05hG5pQ3M5iUtUtIJtZU4rfvFi9cq+rzlOn48+MkrOEnCnb3yrZBDBHpAiMgpr0I7R0A2DubFShjtIAQ49MJQSSU2PzGCfCHGrAH27JhRtRD9C2m2HEfNb+yajeoucuHKBBCdc9Mi0psNES6mtNwlODajRvP427obFzLrOCTz3rTvNQNfDYeo/5mAMA2pu8kAcqzKPUkdo0dkGxs3bBVtxzULqyqB1RUnjftpjG22S+LX+aS0jyL/PWWYdfpwmZYol46l/V+k4L2rwBumsKUJ5nDwuI5+ol2BtZWpUiOruossZgyK5dfrxXDqyMlSCqRvr5FMujg8bj6gKgo5+amWeLA0cGhCe7kwm8c2HWV+Xadn2eEbKTITQBEpM/AeLYOh1twmNN4YXAlAkPccSj0W1VD/1hLR6csXVcmpDr687yfABRQcIywCiIgwUV3YZPOOQYacBvbNZfWGNLgnUZjIjI3PM4jEzFh7UTriu7A93CKr7fz6HahDnAl0mVk2/ihnsHkMteHjRzu86pJRu3erUeKtywLF1tLhSnuQJodSjIW/UoLubuMgtB0+H/RG8WN3XhoZWMCFhfamimBChiMmlrtWX4x+ta6hN7gZRUCFYAO4nCPzgege39Fjt1FLPqmCDberupexwUjO9/09fpP8tbS0zXKZfvtCZonPTEd1cv4vOApiXrhrEo6Xb6gwkbeC+Z7/8gDpopoA8JR2P/ZFIPdIHCT4QayTkKDSciSZCLlZPMznk680qe+77qsKebCW+E/HnNJkjzFDLJt+jh9UhrlqoEzsf7L+NXRdi0Yy9xGSQNaJDQTGFqRn8YChRwOVcC0
image:
    repository: bwalia/whitefalcon
    pullPolicy: Always
    tag: latest
imagePullSecrets: {  }
nameOverride: ''
fullnameOverride: ''
storage:
    enabled: false
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: ''
serviceAccount:
    create: true
    annotations: {  }
    name: ''
podAnnotations: {  }
podSecurityContext: {  }
securityContext: {  }
service:
    type: ClusterIP
    port: 80
ingress:
    enabled: true
    className: traefik
    annotations: { cert-manager.io/cluster-issuer: letsencrypt-production, kubernetes.io/ingress.class: traefik }
    hosts: [{ host: front.int.diycdn.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: int.diycdn.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: qa.int.diycdn.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: www.int.workstationcrm.com, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: int.workstation.co.uk, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: int.odincm.com, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }, { host: nodeapp.int.diycdn.org, paths: [{ path: /, pathType: ImplementationSpecific, serviceName: wf-front-svc-int, servicePort: 80 }] }]
    tls: [{ secretName: nodeapp-int-tls-secret, hosts: [nodeapp.int.diycdn.org] }, { secretName: odincm-int-tls-secret, hosts: [int.odincm.com] }, { secretName: wsw-int-tls-secret, hosts: [int.workstation.co.uk] }, { secretName: wsl-int-tls-secret, hosts: [www.int.workstationcrm.com] }, { secretName: wf-qa-int-tls-secret, hosts: [qa.int.diycdn.org] }, { secretName: wf-int-tls-secret, hosts: [int.diycdn.org] }, { secretName: wf-front-int-tls-secret, hosts: [front.int.diycdn.org] }]
resources: {  }
autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
nodeSelector: {  }
tolerations: {  }
affinity: {  }
