apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whitefalcon-router.fullname" . }}
  labels:
    {{- include "whitefalcon-router.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "whitefalcon-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "whitefalcon-router.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.app.name }}-cm-{{ .Values.app.target_env }}-vol
          # Populate the volume with config map data
          configMap:
            # `name` here must match the name 
            # specified in the ConfigMap's YAML 
            name: {{ .Values.app.name }}-cm-{{ .Values.app.target_env }}
        - name: openresty-vol-{{ .Values.app.target_env }}
          secret:
            secretName: "{{ .Values.app.name }}-secret-{{ .Values.app.target_env }}"
            items:
            - key: env_file
              path: .env
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whitefalcon-router.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "stat -c %a /tmp && ls -la /tmp && cp /tmp/configmap/bootstrap-openresty.sh /usr/local/bin/bootstrap-openresty.sh && chmod +x /usr/local/bin/bootstrap-openresty.sh && bash /usr/local/bin/bootstrap-openresty.sh"]
          volumeMounts:
            - name: {{ .Values.app.name }}-cm-{{ .Values.app.target_env }}-vol
              mountPath: /tmp/configmap
            - name: openresty-vol-{{ .Values.app.target_env }}
              mountPath: /tmp/secrets
          env:
          - name: DNS_RESOLVER
            value: "{{ .Values.app.dns_resolver }}"
          - name: REDIS_HOST
            value: "{{ .Values.app.redis_host }}"            
          - name: APP_NAME
            value: "{{ .Values.app.name }}"  
          - name: VERSION
            value: "{{ .Values.app.version }}"  
          - name: STACK
            value: "Lua 5.1"  
          - name: API_URL
            value: "{{ .Values.app.api_url }}"  
          - name: VITE_DEPLOYMENT_TIME
            value: "{{ now | date "20060102150405" }}"
          - name: NGINX_CONFIG_DIR
            value: "/opt/nginx/"
          - name: JWT_SECURITY_PASSPHRASE
            value: "{{ .Values.app.jwt_security_passphrase }}"

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
