services:
  cypress-chrome:
    image: cypress/included:13.6.4
    command: "--browser chrome"
    working_dir: /cypress
    volumes:
      - ./:/cypress
    env_file: .env
  cypress-firefox:
    image: cypress/included:13.6.4
    command: "--browser firefox"
    working_dir: /cypress
    volumes:
      - ./:/cypress/
    env_file: .env
  cypress-electron:
    image: cypress/included:13.6.4
    working_dir: /cypress
    volumes:
      - ./:/cypress/
    env_file: .env     
