apiVersion: v1
kind: ConfigMap
metadata:
  name: openresty-bootstrap-cm-{{ .Values.app.target_env }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-openresty.sh: |
        #!/bin/bash
        set -x
        # Set Resolver for nginx
        cp /tmp/resolver.conf ~/resolver_backup.conf && sed -i -e 's/Docker resolver/K3S resolver/' /tmp/resolver.conf && sed -i -e 's/resolver 127.0.0.11/resolver {{ .Values.app.dns_resolver }}/' /tmp/resolver.conf
        # Set Timezone
        echo "Openresty WhiteFalcon Nginx Bootstrap Script"
        echo "==========================="
        FILE=/usr/local/openresty/nginx/html/openresty-admin/.env
        cp /tmp/secrets/.env $FILE
        echo "==========================="
        echo "Openresty WhiteFalcon Src copy to /var/www/html Complete"
        cd /usr/local/openresty/nginx/html/openresty-admin/ && yarn build
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        echo "==========================="
        FILE=/tmp/.env
        echo DYNAMIC_SCRIPTS_PATH=/tmp >> $FILE
        echo "==========================="
        echo "Copy openresty config file for Openresty WhiteFalcon"
        echo "==========================="
        echo "Restart openresty nginx"
        openresty -s reload
        echo "==========================="
        echo "Openresty WhiteFalcon Nginx Bootstrap Script Completed"      
    whitefalcon.conf: |
{{- range .Values.ingress.hosts }}
        # Openresty WhiteFalcon Nginx Conf Openresty WhiteFalcon.conf src ConfigMap loaded by openresty
        server {
        listen         80;
        server_name {{ .host | quote }};
        root  /usr/local/openresty/nginx/html;
        index          index.html;
        location / {
            return 200 "Openresty WhiteFalcon Nginx Conf Openresty WhiteFalcon.conf src ConfigMap loaded by openresty";
        }
        location ~ /\. {
            deny all;
        }
        }
        }
{{- end }}
