######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: whitefalcon-secret-{{ .Values.app.target_env }}
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    env_file: {{ .Values.secure_env_file }}
  template:
    metadata:
      name: whitefalcon-secret-{{ .Values.app.target_env }}
      namespace: {{ .Values.app.namespace }}
    type: Opaque