apiVersion: v1
kind: Service
metadata:
  name: {{ include "whitefalcon.fullname" . }}
  labels:
    {{- include "whitefalcon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "whitefalcon.selectorLabels" . | nindent 4 }}
