- name: Restart openresty
  service:
   name: openresty
   state: restarted
  tags: [ luarocks, openresty ]

- name: Restart consul
  service:
   name: openresty
   state: restarted
  tags: [ consul ]

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags: [ luarocks, openresty ] 
