ubuntu_packages:
  - apt-transport-https
  - ca-certificates

kubectl_manifests:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.0.4/deploy/static/provider/aws/deploy.yaml
