######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "openresty-secret-{{ .Values.app.target_env }}-{{ .Values.app.type }}"
  namespace: {{ .Values.app.namespace }}
spec:
  encryptedData:
    env_file: {{ .Values.secure_env_file }}
  template:
    metadata:
      name: "openresty-secret-{{ .Values.app.target_env }}-{{ .Values.app.type }}"
      namespace: {{ .Values.app.namespace }}
    type: Opaque