- name: load host variables
  include_vars: host_vars/k3s2.edgeone.cloud/vars.yaml
- hosts: nginx_cluster 
  become: yes
  roles:
    - ubuntu 
    - luarocks 
    - powerdns
  vars:
    nginx_port: 80
