- hosts: k3s-cluster 
  become: yes
  # roles:
  #   - ubuntu
  vars:
    k3s_version: "v1.32.2+k3s1"
    k3s_token: "CHANGEME"

- hosts: k3s-masters 
  become: yes
  roles:
    - k3s/master
  vars:
    avarname_masternode: avarvaluemasternode

- hosts: k3s-workers 
  become: yes
  roles:
    - k3s/worker
  vars:
    avarname_workernode: avarvalue_workernode
