galaxy_info:
  author: your_name
  description: Ansible role to copy and execute a script on Alpine Linux
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Alpine
      versions:
        - all
dependencies: []
