local_settings_file_path: "/Users/balinderwalia/Documents/Work/aws_keys/settings_whisky04.json"
local_env_file_path: "/Users/balinderwalia/Documents/Work/aws_keys/.env_whisky04"
nginx_user_password: "!!REDACTED!!" # This is the password for the user www-data but must be encrypted using Ansible Vault
host_lan_ip: "10.24.5.4"