apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-cm-{{ .Values.app.target_env }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-openresty.sh: |
        #!/bin/bash
        set -x
        # Set Resolver for nginx
        cp /tmp/resolver.conf ~/resolver_backup.conf && sed -i -e 's/Docker resolver/K3S resolver/' /tmp/resolver.conf && sed -i -e 's/resolver 127.0.0.11/resolver {{ .Values.app.dns_resolver }}/' /tmp/resolver.conf
        # Set Timezone
        echo "Openresty whitefalcon Nginx Bootstrap Script"
        FILE=/opt/nginx/data/settings.json
        if test -f "$FILE"; then
            echo "$FILE exists."
            echo "==========================="
            echo "Settings Script Exists already"
            echo "==========================="
        else
            echo "Settings Script does not exist. Copy sample-settings.json to settings.json"
            SAMPLE=/opt/nginx/data/sample-settings.json
            if test -f "$SAMPLE"; then
                echo "$SAMPLE exists."
                cp $SAMPLE $FILE
            fi
        fi        
        echo "==========================="
        echo "Copy user data configurations"
        FILE=/opt/nginx/
        cp -r /src/userdata/* $FILE
        if [ -d "$FILE" ]; then
          chmod 755 -R $FILE
          chown nobody:root -R $FILE
        fi
        FILE=/usr/local/openresty/nginx/html/openresty-admin/.env
        cp /tmp/secrets/.env $FILE
        echo "==========================="
        echo "Openresty whitefalcon Src copy to /var/www/html Complete"
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        echo "==========================="
        echo "VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION" >> $FILE
        echo "==========================="
        echo "Update openresty config file for this whitefalcon env"
        echo "==========================="
        echo "Restart openresty nginx"
        echo "Rebuilding yarn"
        cd /usr/local/openresty/nginx/html/openresty-admin/ && yarn build
        echo "Rebuilding done"
        openresty -s reload
        echo "==========================="
        echo "Openresty whitefalcon Nginx Bootstrap Script Completed"
{{- if .Values.app.sync_data_onload -}}
        echo "Openresty data sync"
        sleep 10
        mkdir -p /tmp/opsapi
        touch /tmp/opsapi/sync.log
        curl http://localhost/frontdoor/opsapi/sync >> /tmp/opsapi/sync.log
{{- end }}
    whitefalcon.conf: |
{{- range .Values.ingress.hosts }}
        # Openresty whitefalcon Nginx Conf Openresty whitefalcon.conf src ConfigMap loaded by openresty
        server {
        listen         80;
        server_name {{ .host | quote }};
        root  /usr/local/openresty/nginx/html;
        index          index.html;
        location / {
            return 200 "Openresty whitefalcon Nginx Conf Openresty whitefalcon.conf src ConfigMap loaded by openresty";
        }
        location ~ /\. {
            deny all;
        }
        }
        }
{{- end }}
