local_settings_file_path: "/tmp/settings.json"
local_env_file_path: "/tmp/.env"
nginx_user_password: "!!REDACTED!!" # This is the password for the user www-data but must be encrypted using Ansible Vault
host_lan_ip: "10.24.5.1"
nginx_s3_proxy_pass_host_ip: "192.168.1.13"
nginx_s3_server_name: "s3.workstation.co.uk"
nginx_s3_cli_server_name: "s3-cli.workstation.co.uk"
nginx_k3s_dashboard_server_name: "k3s-dashboard.workstation.co.uk"
