$ANSIBLE_VAULT;1.1;AES256
62363834363637623462393961333931313038653966353061343766393765383065633137326166
3863643230343630313239323166326161373337333935640a333261353634376537343938633738
33373636653466333635656638626635653465363738623464303162383565326230356661363566
3338303035616537380a363565323935663236626639343334633433613432656233316438343362
30343661663864623161666433346365373265643462653539636131643930313062366262336164
65386665393762623436333065663466373564343733326564663137623232363638356533653036
38346630653735343065656538656565346363366430343566356539333632326561313066626461
38643931386535303834383131353439663262376264356138323562326335356364623936633136
36303533623564323766643431613232353430383234633662346265376231363064636266333436
61313834343238323539653961306431653337323862653833336339323264393864623164353061
393364653966666364326166323032356263
