local_settings_file_path: "/tmp/settings_3.9.40.237.json"
local_env_file_path: "/tmp/.env_3.9.40.237"
nginx_user_password: "!!REDACTED!!" # This is the password for the user www-data but must be encrypted using Ansible Vault
