apiVersion: v1
kind: Secret
metadata:
  name: CICD_PROJECT_NAME-settings-CICD_NAMESPACE_PLACEHOLDER
  namespace: CICD_NAMESPACE_PLACEHOLDER
type: Opaque
data:
  settings_sec_env_file: SETTINGS_FILE_BASE64_PLACEHOLDER
