# Common packages for both Ubuntu and Debian
common_packages:
  - python3-pip
  - virtualenv
  - python3-setuptools
  - zlib1g
  - zlib1g-dev
  - libssl-dev
  - rsync
  - cron
  - git
  - curl
  - wget
  - unzip
  - zip
  - jq
  - net-tools
  - iputils-ping
  - dnsutils
  - htop
  - tree
  - dmsetup
  - nfs-common
  - open-iscsi
  - ansible
  - default-jre
  - vim
  - make
  - gcc
  - g++
  - python3
  - npm
  - openssh-server
  - ca-certificates

# Ubuntu-specific packages
ubuntu_specific_packages:
  - software-properties-common
  - libpcre3
  - libpcre3-dev
  - openjdk-21-jdk
  - netcat-traditional

# Debian-specific packages
debian_specific_packages:
  - python3-apt
  - libpcre2-dev
  - openjdk-21-jdk
  - netcat-openbsd
