ubuntu_packages:
  - libpcre3
  - libpcre3-dev
  - zlib1g
  - zlib1g-dev
  - libssl-dev
  - rsync
  - cron
  - git
  - curl
  - wget
  - unzip
  - zip
  - jq
  - net-tools
  - iputils-ping
  - dnsutils
  - htop
  - tree
  - dmsetup
  - nfs-common
  - open-iscsi
  - ansible
  - openjdk-21-jdk
  - default-jre
  - vim
  - make
  - gcc
  - g++
  - python3
  - npm
  - binutils
  - openssh-server
  - netcat-traditional
  - ca-certificates
