######################################################
# Secret: Create Multiples encrypted data
######################################################
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "s3-browser-app-secret"
spec:
  encryptedData:
    env_file: {{ .Values.secure_env_file }}
  template:
    metadata:
      name: "s3-browser-app-secret"
    type: Opaque