apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3-browser-app.fullname" . }}
  labels:
    {{- include "s3-browser-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "s3-browser-app.selectorLabels" . | nindent 4 }}
