name: "Build and Auto Deploy - whitefalcon INT, TEST, ACC"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ feature/* ]

env:
  TARGET_ENV: "int"
  IMAGE_NAME: "whitefalcon"
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: [self-hosted-node2]
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"
      - name: build and run the white falcon docker image
        run: chmod +x ./build.sh && ./build.sh "${{ secrets.DOCKER_USER }}" "${{ secrets.DOCKER_PASSWD }}"

  deploy2:
    runs-on: [self-hosted-node2]
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update the Deployed Environment
        run: |
          HELM_CMD="helm --kubeconfig /home/bwalia/.kube/vpn-k3s2.yaml"
          KUBECTL_CMD="kubectl --kubeconfig /home/bwalia/.kube/vpn-k3s2.yaml"
          VALUES=k3s2
          $HELM_CMD upgrade -i whitefalcon-api-${{ env.TARGET_ENV }}-api ./devops/helm-charts/whitefalcon-api/ -f devops/helm-charts/whitefalcon-api/values-${{ env.TARGET_ENV }}-api-k3s2.yaml --set TARGET_ENV=${{ env.TARGET_ENV }} --namespace ${{ env.TARGET_ENV }} --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-api-${{ env.TARGET_ENV }}-api -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-api-${{ env.TARGET_ENV }}-api -n ${{ env.TARGET_ENV }}
          sleep 60
          $HELM_CMD upgrade -i whitefalcon-api-${{ env.TARGET_ENV }}-router ./devops/helm-charts/whitefalcon-api/ -f devops/helm-charts/whitefalcon-api/values-${{ env.TARGET_ENV }}-router-k3s2.yaml --set TARGET_ENV=test --namespace int --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-api-${{ env.TARGET_ENV }}-router -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-api-${{ env.TARGET_ENV }}-router -n ${{ env.TARGET_ENV }}
          sleep 60
          $KUBECTL_CMD get pods,ing -n test
  
  healthcheck2:
    runs-on: [self-hosted-node2]
    needs: [ deploy2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: http://int2-api.whitefalcon.io/ping
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 
  
  healthcheck2test:
    runs-on: [self-hosted-node2]
    needs: [ deploy2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: https://test-api.whitefalcon.io/ping
          API_PING_NODE: node2
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 

  deploy6:
    runs-on: [self-hosted-node6]
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update the Deployed Environment
        run: |
          HELM_CMD="helm --kubeconfig /home/bwalia/.kube/vpn-k3s6.yaml"
          KUBECTL_CMD="kubectl --kubeconfig /home/bwalia/.kube/vpn-k3s6.yaml"
          VALUES=k3s6
          $HELM_CMD upgrade -i whitefalcon-api-${{ env.TARGET_ENV }}-api ./devops/helm-charts/whitefalcon-api/ -f devops/helm-charts/whitefalcon-api/values-${{ env.TARGET_ENV }}-api-k3s6.yaml --set TARGET_ENV=${{ env.TARGET_ENV }} --namespace ${{ env.TARGET_ENV }} --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-api-${{ env.TARGET_ENV }}-api -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-api-${{ env.TARGET_ENV }}-api -n ${{ env.TARGET_ENV }}
          sleep 60
          $HELM_CMD upgrade -i whitefalcon-api-${{ env.TARGET_ENV }}-router ./devops/helm-charts/whitefalcon-api/ -f devops/helm-charts/whitefalcon-api/values-${{ env.TARGET_ENV }}-router-k3s6.yaml --set TARGET_ENV=test --namespace int --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-api-${{ env.TARGET_ENV }}-router -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-api-${{ env.TARGET_ENV }}-router -n ${{ env.TARGET_ENV }}
          sleep 60
          $KUBECTL_CMD get pods,ing -n test
  
  healthcheck6:
    runs-on: [self-hosted-node6]
    needs: [ deploy6 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: http://int6-api.whitefalcon.io/ping
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 
  
  healthcheck6test:
    runs-on: [self-hosted-node6]
    needs: [ deploy6 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: https://test-api.whitefalcon.io/ping
          API_PING_NODE: node6
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 
      