name: API Test Suite execution on selected env

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'int2'
        required: true
        options: 
          - local 
          - int2
          - int6
          - test
          - acc

      DELETE_TEST_DATA:
        description: 'Delete Test Data After Execution'
        required: true
        default: 'true'
        type: boolean

env:
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'int2'}}
  LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
  JWT_TOKEN_KEY: ${{ secrets.JWT_TOKEN_KEY }}
  DELETE_TEST_DATA: ${{ inputs.DELETE_TEST_DATA }}
  QA_EXPIRED_JWT_TOKEN_KEY: ${{ secrets.QA_EXPIRED_JWT_TOKEN_KEY }}

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup local environment
        run: |  
          ./deploy-to-docker.sh "dev" "whitefalcon"

      - name: API Test For Rules & Servers
        working-directory: ./QA
        run: |  
          if [[ "${{ inputs.TARGET_ENV }}" == 'int2' ]]; then
            export TARGET_HOST="http://api.int2.whitefalcon.io"
            export SERVER_NAME="front.int2.whitefalcon.io"
            export SERVER_ID_QA="host:front.int2.whitefalcon.io"
            export NODE_APP_IP="10.43.140.53:3009"  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'int6' ]]; then
            export TARGET_HOST="http://api.int6.whitefalcon.io"
            export SERVER_NAME="qa.int6.whitefalcon.io"
            export SERVER_ID_QA="host:qa.int6.whitefalcon.io"  
            export NODE_APP_IP="10.43.81.65:3009"  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'test' ]]; then
            export TARGET_HOST="http://api.test6.whitefalcon.io"
            export SERVER_NAME="test6.whitefalcon.io"
            export SERVER_ID_QA="host:test6.whitefalcon.io"
            export NODE_APP_IP=""  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'local' ]]; then
            export TARGET_HOST="http://localhost:8081"
            export SERVER_NAME="localhost"
            export SERVER_ID_QA="host:localhost"  
            export NODE_APP_IP="172.177.0.10:3009"  

          elif [[ "${{ inputs.TARGET_ENV }}" == '' ]]; then
            export TARGET_HOST="http://localhost:8081"
            export SERVER_NAME="localhost"
            export SERVER_ID_QA="host:localhost"  
            export NODE_APP_IP="172.177.0.10:3009"    

          else
            echo "Unsupported TARGET_ENV:${{ inputs.TARGET_ENV }}"
            exit 1
          fi
                     
          go mod init myapp
          go test -v
   