name: "Build and Auto Deploy - whitefalcon INT, TEST, ACC"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ feature/* ]

env:
  TARGET_ENV: "int"
  TARGET_TYPE: "api"
  IMAGE_NAME: "whitefalcon"
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: [self-hosted-node2]
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"
      - name: Deploy whitefalcon api gw to k3s optionally build and push the white falcon docker image
        run: chmod +x ./deploy.sh && ./deploy.sh "${{ secrets.DOCKER_USER }}" "${{ secrets.DOCKER_PASSWD }}" "${{ env.TARGET_ENV }}" "${{ env.TARGET_TYPE }}" "${{ env.IMAGE_NAME }}" "${{ env.IMAGE_TAG }}"
  
  # healthcheck2:
  #   runs-on: [self-hosted-node2]
  #   needs: [ deploy2 ]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19
  #     - name: Ping verification
  #       working-directory: ./QA
  #       env:
  #         API_PING_URL: http://int2-api.whitefalcon.io/ping
  #       run: | 
  #         go mod init myapp
  #         go test whitefalcan-healthcheck_test.go -v 
  
  # healthcheck6test:
  #   runs-on: [self-hosted-node6]
  #   needs: [ deploy6 ]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Go
  #       uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.19
  #     - name: Ping verification
  #       working-directory: ./QA
  #       env:
  #         API_PING_URL: https://test-api.whitefalcon.io/ping
  #         API_PING_NODE: node6
  #       run: | 
  #         go mod init myapp
  #         go test whitefalcan-healthcheck_test.go -v 
                