name: Push Node App Docker Images to Docker

on:
  push:
    branches:
      - dummy

env:
    IMAGE_NAME: "whitefalcon"
    TARGET_IMAGE_TAG: "test"
    TARGET_STACK: openresty_php
    IMAGE_REGISTRY: ${{ secrets.WSL_DOCKER_REGISTRY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.WSL_DOCKER_USER }} -p ${{ secrets.WSL_DOCKER_PASSWD }} ${{ env.IMAGE_REGISTRY }}

      - name: Build Docker image
        run: docker build -f $(pwd)/demos-origins/node-app/Dockerfile --build-arg TAG=latest -t wsl-${{ env.TARGET_STACK }} . --no-cache

      - name: Tag Docker image
        run: docker tag wsl-${{ env.TARGET_STACK }} ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-nodeapp:${{ env.TARGET_IMAGE_TAG }}

      - name: Push Docker image to Docker
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-nodeapp:${{ env.TARGET_IMAGE_TAG }}
