name: "Build and Deploy - Whitefalcon INT, TEST, ACC or PROD"

on:
  push:
    branches: [ dummy ]
  pull_request:
    branches: [ dummy/* ]
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'test'
        required: true
        options:
        - prod
        - test
        - int
        - dev
    
env:
  TARGET_ENV: ${{ github.event.inputs.TARGET_ENV }}
  IMAGE_NAME: "whitefalcon"
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: [self-hosted-node2]
    steps:
      - name: checkout the repo code
        uses: actions/checkout@v2 
        with:
          ref: "main"
      - name: build and run the white falcon docker image
        run: chmod +x ./build.sh && ./build.sh "${{ secrets.DOCKER_USER }}" "${{ secrets.DOCKER_PASSWD }}"

  deploy2:
    runs-on: [self-hosted-node2]
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update the Deployed Environment
        run: |
          if [[ ${{ env.TARGET_ENV }} == "" ]]; then
            echo "TARGET_ENV=test" >> $GITHUB_ENV
          else
            echo "TARGET_ENV is set already by user"
          fi
          HELM_CMD="helm --kubeconfig /home/bwalia/.kube/vpn-k3s2.yaml"
          KUBECTL_CMD="kubectl --kubeconfig /home/bwalia/.kube/vpn-k3s2.yaml"
          VALUES=k3s2
          $HELM_CMD upgrade -i whitefalcon-${{ env.TARGET_ENV }} ./devops/helm-chart/whitefalcon/ -f devops/helm-chart/whitefalcon/values-${{ env.TARGET_ENV }}-k3s2.yaml --set TARGET_ENV=${{ env.TARGET_ENV }} --namespace ${{ env.TARGET_ENV }} --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}
          sleep 60
          $KUBECTL_CMD get pods,ing -n ${{ env.TARGET_ENV }}

  deploy6:
    runs-on: [self-hosted-node6]
    needs: [ build ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update the Deployed Environment
        run: |
          if [[ ${{ env.TARGET_ENV }} == "" ]]; then
            echo "TARGET_ENV=test" >> $GITHUB_ENV
          else
            echo "TARGET_ENV is set already by user"
          fi
          HELM_CMD="helm --kubeconfig /home/bwalia/.kube/vpn-k3s6.yaml"
          KUBECTL_CMD="kubectl --kubeconfig /home/bwalia/.kube/vpn-k3s6.yaml"
          VALUES=k3s6
          $HELM_CMD upgrade -i whitefalcon-${{ env.TARGET_ENV }} ./devops/helm-chart/whitefalcon/ -f devops/helm-chart/whitefalcon/values-${{ env.TARGET_ENV }}-k3s6.yaml --set TARGET_ENV=${{ env.TARGET_ENV }} --namespace ${{ env.TARGET_ENV }} --create-namespace
          sleep 60
          $KUBECTL_CMD rollout restart deployment/whitefalcon-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}
          $KUBECTL_CMD rollout history deployment/whitefalcon-${{ env.TARGET_ENV }} -n ${{ env.TARGET_ENV }}
          sleep 60
          $KUBECTL_CMD get pods,ing -n ${{ env.TARGET_ENV }}
      - name: Slack Notification for Workstation CRM release 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
  healthcheck2:
    runs-on: [self-hosted-node2]
    needs: [ deploy2 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: https://test.whitefalcon.io/ping
          API_PING_NODE: node2
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 

  healthcheck6:
    runs-on: [self-hosted-node2]
    needs: [ deploy6 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Ping verification
        working-directory: ./QA
        env:
          API_PING_URL: https://test.whitefalcon.io/ping
          API_PING_NODE: node6
        run: | 
          go mod init myapp
          go test whitefalcan-healthcheck_test.go -v 
  