name: wslproxy QA UI Tests Suite
on:
  schedule:
    - cron: "0 22 * * *"

  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: "Please choose the Target Environment"
        default: "dev"
        required: true
        options:
          - dev
          - int
          - test
          - acc
          - dockerinternal
      BROWSER:
        type: choice
        description: "Browser to test (all runs Chrome, Firefox, Electron)"
        default: "all"
        required: false
        options:
          - all
          - chrome
          - firefox
          - electron

env:
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'dev' }}
  BROWSER: ${{ inputs.BROWSER || 'chrome' }}

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Compose to run Cypress Test framework specs
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0
          legacy: true

      - name: Setup local environment
        if: ${{ env.TARGET_ENV == 'dockerinternal' }}
        run: |
          echo "spin the wslproxy server"
          ./deploy-to-docker.sh "dockerinternal" "wslproxy" "${{ secrets.JWT_TOKEN_KEY }}"
          docker ps

      - name: Executing UI tests using Cypress Test framework on ${{ env.TARGET_ENV }}
        working-directory: ./QA/cypress_ui_tests
        run: |
          chmod +x ./qa-bootstrap-cypress.sh
          sh ./qa-bootstrap-cypress.sh "${{ secrets.LOGIN_EMAIL }}" "${{ secrets.LOGIN_PASSWORD }}" "${{ env.TARGET_ENV }}" "${{ secrets.JWT_TOKEN_KEY }}" "${{ env.BROWSER }}"
        continue-on-error: true

      - name: Ensure cypress directories exist
        working-directory: ./QA/cypress_ui_tests
        run: |
          mkdir -p cypress/screenshots cypress/videos cypress/downloads
          sudo chmod -R a+rwx cypress/screenshots cypress/videos cypress/downloads

      - name: "Upload screenshots and videos to Slack"
        if: always()
        uses: trymbill/cypress-slack-video-upload-action@v2.1.1
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          channel: "cypress-test-results"
          screenshotsDir: QA/cypress_ui_tests/cypress/screenshots
          videosDir: QA/cypress_ui_tests/cypress/videos
          message-text: "QA Cypress UI test finished for wslproxy on ${{ env.TARGET_ENV }} environment. Screenshots and videos are attached."
