name: Whitefalcon QA UI Tests Suite
on:
  schedule:
    - cron: '0 22 * * *'
    
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: 'Please choose the Target Environment'
        default: 'int'
        required: true
        options:
          - int
          - test
          - acc
          - dockerinternal
          
env: 
  TARGET_ENV: ${{ inputs.TARGET_ENV || 'int' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose to run Cypress Test framework specs
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`

      - name: Setup local environment
        if: ${{ inputs.TARGET_ENV == 'dockerinternal' }}
        run: |  
          ./deploy-to-docker.sh "dockerinternal" "whitefalcon" "${{ secrets.JWT_TOKEN_KEY }}"
          docker ps

      - name: Executing UI tests using Cypress Test framework on ${{ env.TARGET_ENV }}
        working-directory: ./QA/cypress_ui_tests
        run: |
            docker ps
            chmod +x ./qa-bootstrap-cypress.sh && sh ./qa-bootstrap-cypress.sh "${{ secrets.LOGIN_EMAIL }}" "${{ secrets.LOGIN_PASSWORD }}" "${{ env.TARGET_ENV }}" "${{ secrets.JWT_TOKEN_KEY }}"

      - name: 'Upload screenshots and videos to Slack'
        uses: trymbill/cypress-slack-video-upload-action@v1.3.0
        with:
            token: ${{ secrets.SLACK_TOKEN }}
            channels: 'cypress-test-results'
            workdir: ./QA/cypress_ui_tests

      - name: Slack Notification for Whitefalcon QA UI Tests using Cypress 
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_CHANNEL: general
            SLACK_COLOR: ${{ job.status }}
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Whitefalcon QA UI test suite executed on ${{ env.TARGET_ENV }} env using Cypress :rocket:'
            SLACK_TITLE: Whitefalcon QA UI Test Suite Execution On ${{ env.TARGET_ENV }}
            SLACK_USERNAME: rtCamp
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  
