name: Deploy Syn POP v2 environment using Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [syn-control-node]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Build and run Deploy Syn POP v2 TEST environment
        run: |
          docker-compose --env-file .env.syntest -f docker-compose-syntst.yml up -d --build
          docker-compose --env-file .env.syntest ps

    #   - name: Build and run Deploy Syn POP v2 ACC environment
    #     run: |
    #       docker-compose --env-file .env.synacc -f docker-compose-synacc.yml up -d --build
    #       docker-compose --env-file .env.syntest ps
            
      - name: Run tests
        run: |
          echo "Running tests..."    