name: API authentication test

on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: "Please choose the Target Environment"
        default: "local"
        required: true
        options:
          - local
          - int2
          - int6
          - test
          - acc
          - prod
      EXECUTE_FUNCTION:
        description: "Delete Rules After Execution"
        required: true
        default: true
        type: boolean

env:
  TARGET_ENV: ${{ inputs.TARGET_ENV }}
  LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
  JWT_TOKEN_KEY: ${{ secrets.JWT_TOKEN_KEY }}
  EXECUTE_FUNCTION: ${{ inputs.EXECUTE_FUNCTION }}
  QA_EXPIRED_JWT_TOKEN_KEY: ${{ secrets.QA_EXPIRED_JWT_TOKEN_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup local environment
        run: |
          ./deploy-to-docker.sh "dev" "wslproxy" "${{ secrets.JWT_TOKEN_KEY }}"

      - name: API Test For Rules & Servers
        working-directory: ./QA
        run: |
          if [[ "${{ inputs.TARGET_ENV }}" == 'int2' ]]; then
            export TARGET_HOST="http://api-int.wslproxy.com"
            export SERVER_NAME="qa.int2.wslproxy.com"
            export SERVER_ID_QA="host:qa.int2.wslproxy.com"
            export NODE_APP_IP=""  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'int6' ]]; then
            export TARGET_HOST="http://api-int.wslproxy.com"
            export SERVER_NAME="qa.int.wslproxy.com"
            export SERVER_ID_QA="host:qa.int.wslproxy.com"  
            export NODE_APP_IP="10.43.81.65:3009"  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'test' ]]; then
            export TARGET_HOST="http://api.test6.wslproxy.com"
            export SERVER_NAME="test6.wslproxy.com"
            export SERVER_ID_QA="host:test6.wslproxy.com"
            export NODE_APP_IP=""  

          elif [[ "${{ inputs.TARGET_ENV }}" == 'local' ]]; then
            export TARGET_HOST="http://localhost:8081"
            export SERVER_NAME="localhost"
            export SERVER_ID_QA="host:localhost"  
            export NODE_APP_IP="172.177.0.10:3009"  

          elif [[ "${{ inputs.TARGET_ENV }}" == '' ]]; then
            export TARGET_HOST="http://localhost:8081"
            export SERVER_NAME="localhost"
            export SERVER_ID_QA="host:localhost"  
            export NODE_APP_IP="172.177.0.10:3009"    

          else
            echo "Unsupported TARGET_ENV:${{ inputs.TARGET_ENV }}"
            exit 1
          fi
                     
          go mod init myapp
          go test 11_entire_api_crud_test.go 10_token_Validation_test.go -v
