name: API authentication test

on:
  workflow_dispatch:
    inputs:
      TARGET_ENV:
        type: choice
        description: "Please choose the Target Environment"
        default: "dev"
        required: true
        options:
          - dev
          - local
          - int2
          - int6
          - test
          - acc
          - prod
      LOGIN_EMAIL:
        description: "Login Email (leave empty to use secret)"
        required: false
        type: string
      LOGIN_PASSWORD:
        description: "Login Password (leave empty to use secret)"
        required: false
        type: string
      EXECUTE_FUNCTION:
        description: "Delete Rules After Execution"
        required: true
        default: true
        type: boolean

env:
  TARGET_ENV: ${{ inputs.TARGET_ENV }}
  LOGIN_EMAIL: ${{ inputs.LOGIN_EMAIL || secrets.LOGIN_EMAIL }}
  LOGIN_PASSWORD: ${{ inputs.LOGIN_PASSWORD || secrets.LOGIN_PASSWORD }}
  JWT_TOKEN_KEY: ${{ secrets.JWT_TOKEN_KEY }}
  DELETE_TEST_DATA: ${{ inputs.EXECUTE_FUNCTION }}
  QA_EXPIRED_JWT_TOKEN_KEY: ${{ secrets.QA_EXPIRED_JWT_TOKEN_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup local environment
        run: |
          ./deploy-to-docker.sh "dev" "wslproxy" "${{ secrets.JWT_TOKEN_KEY }}"

      - name: API Test For Rules & Servers
        working-directory: ./QA
        run: |
          if [[ "${{ inputs.TARGET_ENV }}" == 'dev' ]]; then
            export TARGET_HOST="https://dev-our.wslproxy.com"
            export SERVER_NAME="dev-frontend.wslproxy.com"
            export SERVER_ID_QA="host:dev-frontend.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://dev-frontend.wslproxy.com"
            export PROFILE_ID="dev"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'int2' ]]; then
            export TARGET_HOST="https://api-int.wslproxy.com"
            export SERVER_NAME="qa.int2.wslproxy.com"
            export SERVER_ID_QA="host:qa.int2.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://qa.int2.wslproxy.com"
            export PROFILE_ID="int"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'int6' ]]; then
            export TARGET_HOST="https://api-int.wslproxy.com"
            export SERVER_NAME="qa.int.wslproxy.com"
            export SERVER_ID_QA="host:qa.int.wslproxy.com"
            export NODE_APP_IP="10.43.81.65:3009"
            export FRONT_URL="https://qa.int.wslproxy.com"
            export PROFILE_ID="int"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'test' ]]; then
            export TARGET_HOST="https://api-test.wslproxy.com"
            export SERVER_NAME="test6.wslproxy.com"
            export SERVER_ID_QA="host:test6.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://test6.wslproxy.com"
            export PROFILE_ID="test"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'local' ]]; then
            export TARGET_HOST="http://localhost:8081"
            export SERVER_NAME="localhost"
            export SERVER_ID_QA="host:localhost"
            export NODE_APP_IP="172.177.0.10:3009"
            export FRONT_URL="http://localhost:8000"
            export PROFILE_ID="dev"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'acc' ]]; then
            export TARGET_HOST="https://api-acc.wslproxy.com"
            export SERVER_NAME="frontdoor-acc.wslproxy.com"
            export SERVER_ID_QA="host:frontdoor-acc.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://frontdoor-acc.wslproxy.com"
            export PROFILE_ID="acc"

          elif [[ "${{ inputs.TARGET_ENV }}" == 'prod' ]]; then
            export TARGET_HOST="https://api-prod.wslproxy.com"
            export SERVER_NAME="frontdoor-prod.wslproxy.com"
            export SERVER_ID_QA="host:frontdoor-prod.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://frontdoor-prod.wslproxy.com"
            export PROFILE_ID="prod"

          elif [[ "${{ inputs.TARGET_ENV }}" == '' ]]; then
            export TARGET_HOST="https://api-dev-our.wslproxy.com"
            export SERVER_NAME="frontdoor-dev-our.wslproxy.com"
            export SERVER_ID_QA="host:frontdoor-dev-our.wslproxy.com"
            export NODE_APP_IP=""
            export FRONT_URL="https://frontdoor-dev-our.wslproxy.com"
            export PROFILE_ID="dev"

          else
            echo "Unsupported TARGET_ENV:${{ inputs.TARGET_ENV }}"
            exit 1
          fi

          go test -v -run "Test10_"
